print("STAR WARS NAME GENERATOR")
print()
fName = input("Enter your first name: ").strip().capitalize()
lName = input("Enter your last name: ").strip().lower()
mumName = input("Enter your Mum's maiden name: ").strip().capitalize()
city = input("Enter the city where you were born: ").strip().lower()
print()
print(f"Your Star Wars name is {fName[:3]}{lName[:2]} {mumName[:2]}{city[-3:]}")

print()
everything = input("Enter your first name, last name, Mum's maiden name and the city you were born in: \n")
everything = everything.split()
print()
print(f"Your Star Wars name is {everything[0][0:3]}{everything[1][0:2]} {everything[2][0:2]}{everything[3][-3:]}")