print("__CONTACT INFORMATION__")
print()
contactInfo = {"name":"", "birthDate":"", "teleNo":"", "email":"", "address":""}

contactInfo["name"] = input("Name: ").strip().capitalize()
contactInfo["birthDate"] = input("Date of Birth: ").strip().capitalize()
contactInfo["teleNo"] = input("Telephone number: ").strip()
contactInfo["email"] = input("Email: ")
contactInfo["address"] = input("Address: ")
print()
print("---------------------------------------------")
print()
print("Here's your contact card")
print()
print(f"Name: {contactInfo['name']}")
print(f"DOB: {contactInfo['birthDate']}")
print(f"Tel: {contactInfo['teleNo']}")
print(f"Email: {contactInfo['email']}")
print(f"Address: {contactInfo['address']}")
print()