print("Getting to know you!")
print()
yourName = input("What's your name?: ")
yourFood = input("What's your favourite food?: ")
yourMusic = input("What's your favourite music?: ")
yourPlace = input("Where do you live?: ")
print()
print()
print("You are")
print(yourName)
print("You're probably hungry for")
print(yourFood)
print("and you're definitely getting into the Spirit with")
print(yourMusic)
print("living in the amazing")
print(yourPlace)