print("Tip Calculator")
print()
print("How much was my bill?: ")
bill = float(input())
print()
print("What percentage do you want to tip?: ")
tipPercent = float(input())
print()
print("How many people are in your group?: ")
group = int(input())
print()
tip = int((tipPercent / 100 * bill))
total = int(tip + bill)
splitPay = round(total / group, 2)
print("You each owe me $", splitPay)